# Generated by Django 5.2.6 on 2026-03-09 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kyc_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_back'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_front'),
        ),
    ]
