# Generated by Django 5.2.6 on 2026-03-09 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='cum_copiers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cum_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='market_category',
            field=models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('stocks', 'Stocks'), ('healthcare', 'Healthcare'), ('financial_services', 'Financial Services'), ('options', 'Options'), ('tech', 'Tech'), ('etf', 'ETF'), ('manufacturing', 'Manufacturing')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='master_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('high', 'High Risk'), ('moderate', 'Moderate Risk'), ('balanced', 'Balanced Risk'), ('low', 'Low Risk'), ('safe', 'Safe')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order_type', models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit')], max_length=20)),
                ('position', models.CharField(choices=[('Open Long', 'Open Long'), ('Open Short', 'Open Short'), ('Closed', 'Closed')], max_length=20)),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('open_date', models.DateTimeField()),
                ('close_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('close_date', models.DateTimeField()),
                ('pl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-close_date'],
            },
        ),
        migrations.CreateModel(
            name='TraderAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(blank=True, default='', max_length=20)),
                ('avg_return', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_risk', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('risk_label', models.CharField(blank=True, default='Avg. Risk', max_length=50)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TraderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=150)),
                ('direction', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=10)),
                ('invested', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='trader_tags',
            field=models.ManyToManyField(blank=True, related_name='traders', to='core.tradertag'),
        ),
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('copier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copying', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copiers_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('copier', 'trader')},
            },
        ),
        migrations.CreateModel(
            name='TraderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('trending', 'Trending Investors'), ('rising_stars', 'Rising Stars'), ('most_copied', 'Most Copied by Categories'), ('reliable', 'Reliable Traders'), ('proven', 'Proven Stability')], max_length=20)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'rank'],
                'unique_together': {('trader', 'section')},
            },
        ),
    ]
