# Generated by Django 5.2.6 on 2026-03-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
