# Generated by Django 5.2.6 on 2026-03-13 02:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminwallet',
            name='color',
        ),
        migrations.AlterField(
            model_name='adminwallet',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='adminwallet',
            name='name',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('usdt_trc20', 'USDT (TRC20)'), ('usdt_erc20', 'USDT (ERC20)'), ('bnb', 'BNB (BEP20)'), ('usdc', 'USDC'), ('litecoin', 'Litecoin'), ('ripple', 'Ripple (XRP)'), ('solana', 'Solana'), ('dogecoin', 'Dogecoin'), ('tron', 'Tron (TRX)'), ('polygon', 'Polygon (MATIC)'), ('avalanche', 'Avalanche (AVAX)'), ('bitcoin_cash', 'Bitcoin Cash')], max_length=30),
        ),
    ]
