# Generated by Django 5.2.6 on 2026-03-13 09:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


def clear_trader_related_data(apps, schema_editor):
    """
    Delete all rows from tables whose FK is changing from User → Trader.
    The Trader table will be empty after this migration; run seed_traders afterwards.
    """
    for model_name in [
        "CopyRelationship",
        "PortfolioAllocation",
        "TradeHistory",
        "TraderAsset",
        "TraderPosition",
        "TraderSection",
    ]:
        apps.get_model("core", model_name).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_adminwallet_color_alter_adminwallet_icon_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_trader_related_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='account_assets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='copiers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cum_copiers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cum_earnings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_trader',
        ),
        migrations.RemoveField(
            model_name='user',
            name='market_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='master_pnl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_drawdown',
        ),
        migrations.RemoveField(
            model_name='user',
            name='min_capital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profit_share',
        ),
        migrations.RemoveField(
            model_name='user',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trader_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trading_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='win_rate',
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('avatar_color', models.CharField(blank=True, default='#4a7a6a', max_length=20)),
                ('specialty', models.CharField(blank=True, default='', max_length=120)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('copiers_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('min_capital', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('trading_days', models.PositiveIntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(blank=True, choices=[('high', 'High Risk'), ('moderate', 'Moderate Risk'), ('balanced', 'Balanced Risk'), ('low', 'Low Risk'), ('safe', 'Safe')], default='', max_length=20)),
                ('market_category', models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('stocks', 'Stocks'), ('healthcare', 'Healthcare'), ('financial_services', 'Financial Services'), ('options', 'Options'), ('tech', 'Tech'), ('etf', 'ETF'), ('manufacturing', 'Manufacturing')], default='', max_length=30)),
                ('master_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account_assets', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cum_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cum_copiers', models.PositiveIntegerField(default=0)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trader_tags', models.ManyToManyField(blank=True, related_name='traders', to='core.tradertag')),
            ],
        ),
        migrations.AlterField(
            model_name='copyrelationship',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copiers_rel', to='core.trader'),
        ),
        migrations.AlterField(
            model_name='portfolioallocation',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_allocations', to='core.trader'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to='core.trader'),
        ),
        migrations.AlterField(
            model_name='traderasset',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_assets', to='core.trader'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.trader'),
        ),
        migrations.AlterField(
            model_name='tradersection',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_memberships', to='core.trader'),
        ),
    ]
