# Generated by Django 5.2.6 on 2026-03-15 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_account_assets_remove_user_avatar_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrelationship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='CopyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('trade_type', models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit')], default='Market', max_length=20)),
                ('direction', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], default='Long', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.copyrelationship')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_trades', to='core.trader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
