# Generated by Django 5.2.6 on 2026-03-15 06:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_copy_relationship_status_and_copy_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copytrade',
            name='copy_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='core.copyrelationship'),
        ),
        migrations.AlterField(
            model_name='copytrade',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_trades', to='core.trader'),
        ),
        migrations.AlterField(
            model_name='traderasset',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
    ]
