# Generated by Django 5.2.6 on 2026-03-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_asset_icon_cloudinary_copytrade_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytrade',
            name='category',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('forex', 'Forex'), ('commodities', 'Commodities'), ('crypto', 'Crypto')], default='stocks', max_length=20),
        ),
    ]
