# Generated by Django 5.2.6 on 2026-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_category_to_copytrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invested_value',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profit',
        ),
        migrations.AddField(
            model_name='user',
            name='percentage_roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
