# Generated by Django 5.2.6 on 2026-03-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_profit_invested_add_percentage_roi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copytrade',
            old_name='price',
            new_name='entry',
        ),
        migrations.RemoveField(
            model_name='copytrade',
            name='category',
        ),
        migrations.RemoveField(
            model_name='copytrade',
            name='trade_type',
        ),
        migrations.AddField(
            model_name='copytrade',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('forex', 'Forex')], default='stock', max_length=10),
        ),
        migrations.AddField(
            model_name='copytrade',
            name='duration',
            field=models.CharField(choices=[('2m', '2 Minutes'), ('5m', '5 Minutes'), ('10m', '10 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('2h', '2 Hours'), ('4h', '4 Hours'), ('6h', '6 Hours'), ('12h', '12 Hours'), ('1d', '1 Day'), ('3d', '3 Days'), ('1w', '1 Week')], default='1h', max_length=10),
        ),
        migrations.AddField(
            model_name='copytrade',
            name='earning_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='copytrade',
            name='direction',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=10),
        ),
    ]
