# Generated by Django 5.2.6 on 2026-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_copytrade_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plaintext',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
