# Generated by Django 5.2.6 on 2026-04-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_password_plaintext'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyCopier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_copiers', to='core.trader')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
