# Generated by Django 6.0.5 on 2026-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dummycopier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdraw_from',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
