# Generated by Django 6.0.5 on 2026-06-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_withdraw_from_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=18),
        ),
    ]
