# Generated by Django 6.0.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_target_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='target',
        ),
    ]
