# Generated by Django 6.0.5 on 2026-07-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_stockprofile_stockquote_stockhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='news',
            new_name='core_news_publish_ff08d5_idx',
            old_name='news_published_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='core_news_categor_d0a088_idx',
            old_name='news_category_idx',
        ),
    ]
