# Generated by Django 6.0.5 on 2026-08-10 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_copytrade_asset_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderposition',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
